version: "3.9"

services:
  db:
    container_name: mysql-spring-barbertime
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: curso_spring
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
