server:
  port: 8080

spring:
  application:
    name: BarberTime

  datasource:
    url: jdbc:mysql://localhost:3306/barbertime?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
